paces-online:
  security:
    token:
      issuer: paces-online-local
      access-token-expiration: 15m
      refresh-token-expiration: 7d

logging:
  level:
    com.pacesonline.identityservice: DEBUG

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pacesonline_identity}
    username: ${DB_USERNAME:pacesonline}
    password: ${DB_PASSWORD:pacesonline}