spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pacesonline_runs}
spring.datasource.username=${DB_USERNAME:pacesonline}
spring.datasource.password=${DB_PASSWORD:pacesonline}

logging.level.com.pacesonline.runservice=DEBUG

paces-online.security.token.issuer=${JWT_ISSUER:https://identity.pacesonline.local}
paces-online.security.token.public-key-location=${JWT_PUBLIC_KEY_LOCATION:file:./config/keys/access-token-public.pem}