spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pacesonline_runs}
spring.datasource.username=${DB_USERNAME:pacesonline}
spring.datasource.password=${DB_PASSWORD:pacesonline}

logging.level.com.pacesonline.runservice=DEBUG